from typing import Dict, List
from datetime import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from utils import logger, Config

class ReportGenerator:    
    def __init__(self):
        self.logger = logger
    
    def generate_report(
        self,
        results: Dict,
        output_path: str = None
    ) -> str:
        
        self.logger.info("Generating research report...")
        
        report_parts = [
            self._generate_header(results),
            self._generate_query_summary(results),
            self._generate_papers_section(results),
            self._generate_synthesis_section(results),
            self._generate_footer()
        ]
        
        report = "\n\n".join(report_parts)
        
        if output_path:
            self._save_report(report, output_path)
        
        return report
    
    def _generate_header(self, results: Dict) -> str:
        
        timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        
        header = f"""# PaperMind Research Report

**Generated:** {timestamp}  
**Query:** "{results['query']}"  
**Papers Found:** {results['total_found']}  
**Papers Analyzed:** {results['total_returned']}

---"""
        
        return header
    
    def _generate_query_summary(self, results: Dict) -> str:
        
        processed = results['processed_query']
        
        summary = f"""## Query Analysis

**Original Query:** {results['query']}

**Refined Query:** {processed['refined_query']}

**Key Search Terms:** {', '.join(processed['keywords'][:5])}

**Topic:** {processed['intent'].get('topic', 'General')}  
**Focus:** {processed['intent'].get('focus', 'Overview')}

---"""
        
        return summary
    
    def _generate_papers_section(self, results: Dict) -> str:
        
        papers = results['papers']
        
        section = "## Top Research Papers\n\n"
        
        for i, paper in enumerate(papers, 1):
            title = paper.get('title', 'Untitled')
            authors = ', '.join(paper.get('authors', ['Unknown'])[:3])
            if len(paper.get('authors', [])) > 3:
                authors += ', et al.'
            
            published = paper.get('published', 'Unknown date')
            url = paper.get('url', '')
            
            section += f"### {i}. {title}\n\n"
            
            section += f"**Authors:** {authors}  \n"
            section += f"**Published:** {published}  \n"
            
            if 'citation_count' in paper and paper['citation_count'] > 0:
                section += f"**Citations:** {paper['citation_count']}  \n"
            
            if 'similarity_score' in paper:
                relevance = paper['similarity_score'] * 100
                section += f"**Relevance Score:** {relevance:.1f}%  \n"
            
            section += f"**Source:** {paper.get('source', 'Unknown')}  \n"
            
            if url:
                section += f"**URL:** [{url}]({url})  \n"
            
            section += "\n"
            
            summary = paper.get('summary', paper.get('abstract', 'No summary available')[:300])
            section += f"**Summary:**  \n{summary}\n\n"
            
            abstract = paper.get('abstract', '')
            if abstract and abstract != summary:
                section += f"**Abstract Excerpt:**  \n> {abstract[:200]}...\n\n"
            
            section += "---\n\n"
        
        return section
    
    def _generate_synthesis_section(self, results: Dict) -> str:
        
        synthesis = results.get('theme_synthesis', '')
        
        if not synthesis:
            return ""
        
        section = f"""## Research Themes & Insights

{synthesis}

---"""
        
        return section
    
    def _generate_footer(self) -> str:
        
        footer = f"""## About This Report

This research report was automatically generated by **PaperMind**, an AI-powered research assistant.

**How it works:**
1. Natural language query processing using AI
2. Multi-source paper fetching (arXiv, Semantic Scholar)
3. Semantic ranking using vector embeddings
4. AI-powered summarization and synthesis

**Powered by:**
- LLM: Ollama (Llama 3.2 3B)
- Embeddings: sentence-transformers/all-MiniLM-L6-v2
- Vector Store: ChromaDB

---

*Note: Summaries and synthesis are AI-generated. Always verify key claims with original papers.*"""
        
        return footer
    
    def _save_report(self, report: str, output_path: str):

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        self.logger.info(f"Report saved to: {output_path}")

if __name__ == "__main__":
    print("Testing ReportGenerator...")
    
    mock_results = {
        'query': 'transformer neural networks',
        'processed_query': {
            'refined_query': 'Transformer architectures in deep learning',
            'keywords': ['transformer', 'attention', 'neural networks', 'deep learning'],
            'intent': {
                'topic': 'Machine Learning',
                'focus': 'Architecture'
            }
        },
        'papers': [
            {
                'title': 'Attention Is All You Need',
                'authors': ['Vaswani', 'Shazeer', 'Parmar'],
                'published': '2017-06-12',
                'url': 'https://arxiv.org/abs/1706.03762',
                'citation_count': 50000,
                'similarity_score': 0.95,
                'source': 'arXiv',
                'abstract': 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks.',
                'summary': 'This paper introduces the Transformer architecture, which relies solely on attention mechanisms.'
            },
            {
                'title': 'BERT: Pre-training of Deep Bidirectional Transformers',
                'authors': ['Devlin', 'Chang', 'Lee'],
                'published': '2018-10-11',
                'url': 'https://arxiv.org/abs/1810.04805',
                'citation_count': 40000,
                'similarity_score': 0.88,
                'source': 'arXiv',
                'abstract': 'We introduce BERT, a new language representation model.',
                'summary': 'BERT uses bidirectional training of Transformers for language understanding tasks.'
            }
        ],
        'theme_synthesis': 'Common themes include the use of attention mechanisms, bidirectional context, and pre-training strategies.',
        'total_found': 20,
        'total_returned': 2
    }
    
    generator = ReportGenerator()
    report = generator.generate_report(mock_results)
    
    print("\n" + "="*70)
    print("GENERATED REPORT")
    print("="*70 + "\n")
    print(report)
    
    output_path = Config.OUTPUT_DIR / "test_report.md"
    generator.generate_report(mock_results, output_path=str(output_path))
    
    print("\n" + "="*70)
    print(f" Report saved to: {output_path}")
    print("="*70)